import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "./_utils/AuthContext";
import "./globals.css";
import { Montserrat } from "next/font/google";

// Load Montserrat with specific weights
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat", // Optional: Define a CSS variable
  display: "swap", // Prevents layout shift
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`montserrat.variable`}>{children}</body>
      </html>
    </AuthProvider>
  );
}
